import numpy as np
n=np.arange(9,dtype=np.float64).reshape(3,3)
print(n)
print('\n')
b=np.array([10,10,10])
print('second array ')
print(b)
print('\n')
print('add 2 arrays')
print(np.add(n,b))
print('\n')
print('subtract 2 arrays')
print(np.subtract(n,b))
print('\n')
print('multiply 2 arrays')
print(np.multiply(n,b))
print('\n')
print('divide 2 arrays')
print(np.divide(n,b))
print('\n')