file=open("demo.txt",'r')
print(file.read())
file.close()
file=open("demo.txt",'r')
print("\n Read in parts \n")
print(file.read(12))
file.close()
file=open("demo.txt",'a')
file.write("Espresso Signora 1234 HAHA tung tung")
file.close()
