file=open("demo.txt",'r')
print("File in  read mode: ")
print(file.read())
file.close()
file_W=open("demo.txt",'w')
print("FILE IN WRITE MODE")
file_W.write("Hi brotha sigmaaaa")
file_W.write("Hi brotha sigmaaaa 2")
file_W.close()
file_A=open("demo.txt",'a')
print("FILE IN append MODE")
file_A.append("Hi brotha sigmaaaa 3 brothaa appendddd hehehehhh")
file_A.close()
